### ISSUE TITLE
http://charlie-duong.com is no longer available?

### ISSUE THREAD

**Issue by softdev999** [charlieduong94/React-Native-Manga-App#1]
Hi Charlie, How are you?
I am very interested in your react-native manga reader app.
But I noticed your development server is no longer available.
Could you please share me the server code as well?
I would highly appreciate your help on it.
Thanks
@Softdev

**Comment by ctdio** [comment]
Hi @softdev999. I have some of the old code in a separate project ([link](https://github.com/charlieduong94/marko-manga-web-app)). Most of the code you care about should be under `routes.js`, `server.js` and `src/api`. That project, much like this one, is unfinished because I was just using it as an excuse to get my feet wet with some different tech.

IIRC, it was just a lightweight api over the data that MangaEden provides. The code is pretty old and not very clean IMO (for both of these projects really 😦 ), but you should be able to pick out parts of it that you need/want. Have fun!

**Comment by softdev999** [comment]
Hi @charlieduong94 
Thank you very much for your help.
I would highly appreciate if you also have some other sample code related to the Magna reading app.
Again, thank you
My Best,
@softdev
